version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: 4rkad-electrs-liquid_web_1
      APP_PORT: 8080

  web:
    image: nginx:1.27-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/web/index.html:/tmp/index.template.html:ro
      - ${APP_DATA_DIR}/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/icon.svg:/usr/share/nginx/html/icon.svg:ro
      - ${APP_DATA_DIR}/web/umbrel-qr-icon.svg:/usr/share/nginx/html/umbrel-qr-icon.svg:ro
    environment:
      ELECTRS_TOR_ADDRESS: "${APP_ELECTRS_LIQUID_RPC_HIDDEN_SERVICE}"
      ELECTRS_LIQUID_VERSION: "${APP_ELECTRS_LIQUID_VERSION}"
    command: ["sh", "-c", "envsubst '$$ELECTRS_TOR_ADDRESS $$ELECTRS_LIQUID_VERSION' < /tmp/index.template.html > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]

  electrs:
    image: ghcr.io/4rkad/electrs-liquid:latest
    restart: always
    ports:
      - "60601:60601"
    stop_grace_period: 30s
    mem_limit: 4g
    volumes:
      - "${APP_DATA_DIR}/data/electrs:/data"
      - "${APP_DATA_DIR}/../elements/data:/data/.bitcoin:ro"
    command:
      - -vv
      - --network
      - liquid
      - --daemon-rpc-addr
      - "elements_node_1:7041"
      - --cookie
      - "elements:${APP_ELECTRS_LIQUID_ELEMENTS_RPC_PASS}"
      - --electrum-rpc-addr
      - "0.0.0.0:60601"
      - --http-addr
      - "0.0.0.0:3000"
      - --db-dir
      - /data/db
      - --db-block-cache-mb
      - "2"
      - --db-write-buffer-size-mb
      - "64"
      - --daemon-parallelism
      - "4"
      - --jsonrpc-import

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
