server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /tor-hostname {
        alias /run/tor-hostname;
        default_type text/plain;
        add_header Cache-Control "no-cache";
    }
}
